import http from 'http';
import { Express } from 'express';
import Database from 'better-sqlite3';
import { KeyService } from '../../src/services/keyService';
import { createTestApp, startTestServer, stopTestServer, authRequest, createBootstrapKey, AuditService } from './setup';

describe('Audit routes', () => {
  let app: Express;
  let db: Database.Database;
  let keyService: KeyService;
  let auditService: AuditService;
  let server: http.Server;
  let baseUrl: string;
  let authToken: string;

  // Track created key IDs for filter tests
  let keyId1: string;
  let keyId2: string;

  beforeAll(async () => {
    const ctx = createTestApp();
    app = ctx.app;
    db = ctx.db;
    keyService = ctx.keyService;
    auditService = ctx.auditService;
    const srv = await startTestServer(app);
    server = srv.server;
    baseUrl = srv.baseUrl;

    // Create a bootstrap key for authentication
    authToken = await createBootstrapKey(keyService, 'audit-test-user');

    // Seed data: create two keys and revoke one to generate multiple audit entries
    const res1 = await authRequest(baseUrl, 'POST', '/api/keys', authToken, {
      keyName: 'audit-test-1',
      scopes: ['read'],
    });
    keyId1 = res1.body.data.keyId;

    const res2 = await authRequest(baseUrl, 'POST', '/api/keys', authToken, {
      keyName: 'audit-test-2',
      scopes: ['write'],
    });
    keyId2 = res2.body.data.keyId;

    // Revoke the second key to produce a key.revoked audit entry
    await authRequest(baseUrl, 'PUT', `/api/keys/${keyId2}/revoke`, authToken, {
      reason: 'test revocation',
    });
  });

  afterAll(async () => {
    await stopTestServer(server);
    db.close();
  });

  // ── GET /api/audit ─────────────────────────────────────────────────

  describe('GET /api/audit', () => {
    it('returns 200 with an array of audit logs', async () => {
      const res = await authRequest(baseUrl, 'GET', '/api/audit', authToken);

      expect(res.status).toBe(200);
      expect(res.body.success).toBe(true);
      expect(Array.isArray(res.body.data)).toBe(true);
      // We created bootstrap key + 2 keys + revoked 1 = at least 3 audit entries
      expect(res.body.data.length).toBeGreaterThanOrEqual(3);
    });

    it('filters by action', async () => {
      const res = await authRequest(baseUrl, 'GET', '/api/audit?action=key.revoked', authToken);

      expect(res.status).toBe(200);
      expect(res.body.success).toBe(true);
      expect(Array.isArray(res.body.data)).toBe(true);
      expect(res.body.data.length).toBeGreaterThanOrEqual(1);
      for (const entry of res.body.data) {
        expect(entry.action).toBe('key.revoked');
      }
    });

    it('filters by keyId', async () => {
      const res = await authRequest(baseUrl, 'GET', `/api/audit?keyId=${keyId1}`, authToken);

      expect(res.status).toBe(200);
      expect(res.body.success).toBe(true);
      expect(Array.isArray(res.body.data)).toBe(true);
      expect(res.body.data.length).toBeGreaterThanOrEqual(1);
      for (const entry of res.body.data) {
        expect(entry.keyId).toBe(keyId1);
      }
    });

    it('supports limit pagination', async () => {
      const res = await authRequest(baseUrl, 'GET', '/api/audit?limit=1', authToken);

      expect(res.status).toBe(200);
      expect(res.body.data.length).toBe(1);
    });

    it('supports offset pagination', async () => {
      // Get a page with no offset
      const noOffset = await authRequest(baseUrl, 'GET', '/api/audit?limit=100', authToken);
      expect(noOffset.status).toBe(200);
      const total = noOffset.body.data.length;
      expect(total).toBeGreaterThan(1);

      // With a large offset, should return fewer results
      const withOffset = await authRequest(baseUrl, 'GET', `/api/audit?limit=100&offset=${total}`, authToken);
      expect(withOffset.status).toBe(200);
      // Offset past the original total may still return entries from KEY_ACCESSED
      // generated by the requests themselves, but should return fewer than total
      expect(withOffset.body.data.length).toBeLessThan(total);
    });

    it('returns empty array when no logs match filter', async () => {
      const res = await authRequest(baseUrl, 'GET', '/api/audit?keyId=nonexistent-key-id', authToken);

      expect(res.status).toBe(200);
      expect(res.body.data).toEqual([]);
    });

    it('supports combined filters (keyId + action)', async () => {
      const res = await authRequest(
        baseUrl,
        'GET',
        `/api/audit?keyId=${keyId2}&action=key.revoked`,
        authToken,
      );

      expect(res.status).toBe(200);
      expect(res.body.data.length).toBeGreaterThanOrEqual(1);
      for (const entry of res.body.data) {
        expect(entry.keyId).toBe(keyId2);
        expect(entry.action).toBe('key.revoked');
      }
    });
  });
});
